Content.destroy_all
Content.create!([
  {name: "Blue Ocean Strategy  ", desc: "The global phenomenon, embraced by business worldwide and now published in more than 40 languages.\r\n\r\nThis international bestseller challenges everything you thought you knew about the requirements for strategic success.\r\n\r\nSince the dawn of the industrial age, companies have engaged in head-to-head competition in search of sustained, profitable growth. They have fought for competitive advantage, battled over market share, and struggled for differentiation. Yet, as this influential and immensely popular book shows, these hallmarks of competitive strategy are not the way to create profitable growth in the future.\r\n\r\nIn the international bestseller Blue Ocean Strategy, W. Chan Kim and Renee Mauborgne argue that cutthroat competition results in nothing but a bloody red ocean of rivals fighting over a shrinking profit pool. Based on a study of 150 strategic moves (spanning more than 100 years across 30 industries), the authors argue that lasting success comes not from battling competitors, but from creating \"blue oceans\"—untapped new market spaces ripe for growth. Such strategic moves, which the authors call “value innovation,” create powerful leaps in value that often render rivals obsolete for more than a decade.\r\n\r\nBlue Ocean Strategy presents a systematic approach to making the competition irrelevant and outlines principles and tools any company can use to create and capture their own blue oceans. A landmark work that upends traditional thinking about strategy, this bestselling business book charts a bold new path to winning the future.", image_url: "http://rdemarketing.com/wp-content/uploads/2013/10/blue-ocean.jpg", source_url: "http://www.amazon.com/Blue-Ocean-Strategy-Uncontested-Competition-ebook/dp/B004OC07F8/", content_type: 1},
  {name: "Competitive Strategy", desc: "Now beyond its eleventh printing and translated into twelve languages, Michael Porter’s The Competitive Advantage of Nations has changed completely our conception of how prosperity is created and sustained in the modern global economy. Porter’s groundbreaking study of international competitiveness has shaped national policy in countries around the world. It has also transformed thinking and action in states, cities, companies, and even entire regions such as Central America.", image_url: "/assets/Compstrat.jpg", source_url: "http://goo.gl/wXdJbF", content_type: 1},
  {name: "Corporate Finance ", desc: "Corporate Finance, by Ross, Westerfield, and Jaffe emphasizes the modern fundamentals of the theory of finance, while providing contemporary examples to make the theory come to life. The authors aim to present corporate finance as the working of a small number of integrated and powerful intuitions, rather than a collection of unrelated topics. They develop the central concepts of modern finance: arbitrage, net present value, efficient markets, agency theory, options, and the trade-off between risk and return, and use them to explain corporate finance with a balance of theory and application. The Tenth Edition includes many exciting new research findings as well as an enhanced Connect Finance, now with even more student learning resources.", image_url: "http://ecx.images-amazon.com/images/I/51fhQvMZ4VL._SY300_.jpg", source_url: "http://www.amazon.com/Corporate-Finance-Mcgraw-Hill-Series-Insurance/dp/0078034779/", content_type: 1},
  {name: "From Values to Action: The Four Principles of Values-Based Leadership ", desc: "ilver Medal Winner, Business and Leadership, 2012 Nautilus Book Awards\r\n\r\nRespected former CEO, professor, and speaker examines what it takes to become a values-based leader\r\n\r\nIn this highly-anticipated book, Harry Kraemer argues that today's business environment demands values-based leaders who, in \"doing the right thing,\" deliver outstanding and lasting results. The journey to becoming a values-based leader starts with self-reflection. He asks, \"If you are not self-reflective, how can you know yourself? If you do not know yourself, how can you lead yourself? If you cannot lead yourself, how can you lead others?\" Kraemer identifies self-reflection as the first of four principles that guide leaders to make choices that honor their values and candidly recounts how these principles helped him navigate some of the toughest challenges he faced in his career.\r\n\r\nOffers a framework for adopting the principles of values-based leadership—self-reflection, balance, true self-confidence, and genuine humility—to lead organizations effectively\r\nBased on Kraemer's popular Kellogg MBA course on values-based leadership\r\nA recognized expert in values-based leadership, Kraemer is a sought after speaker on the subject\r\nLively and engaging, Kraemer's book comes at a critical time when true leadership in every facet of society is desperately needed.\r\n", image_url: "http://ecx.images-amazon.com/images/I/51Ew1OwyjfL._BO2,204,203,200_PIsitb-sticker-v3-big,TopRight,0,-55_SX278_SY278_PIkin4,BottomRight,1,22_AA300_SH20_OU01_.jpg", source_url: "http://www.amazon.com/Values-Action-Principles-Values-Based-Leadership-ebook/dp/B004SHOHT6", content_type: 1},
  {name: "Mastering the building blocks of strategy", desc: "Increase your likelihood of developing effective strategies through an approach that’s thorough, action-oriented, and comfortable with debate and ambiguity.\r\n", image_url: "http://a2.mzstatic.com/us/r30/Purple/v4/fe/83/85/fe83856e-87a8-4f1b-82c6-aebddf310c6b/mzl.lzxwbexk.png", source_url: "http://www.mckinsey.com/insights/strategy/mastering_the_building_blocks_of_strategy", content_type: 2},
  {name: "Operations Management (Operations and Decision Sciences)", desc: "The Eleventh Edition of Stevenson’s Operations Management features integrated, up-to-date coverage of current topics and industry trends, while preserving the core concepts that have made the text the market leader in this course for over a decade. Stevenson’s careful explanations and approachable format support students in understanding the important operations management concepts as well as applying tools and methods with an emphasis on problem solving. Through detailed examples and solved problems, short cases and readings on current issues facing businesses, and auto-gradable end of chapter problems and application-oriented assignments available in Connect Operations Management, students learn by doing, and the Eleventh Edition continues to offer more support for 'doing Operations' than any other.", image_url: "http://ecx.images-amazon.com/images/I/51EnpMEm3xL._AA278_PIkin4,BottomRight,-31,22_AA300_SH20_OU01_.jpg", source_url: "http://www.amazon.com/Operations-Management-Decision-Sciences-ebook/dp/B005MQXZCC/", content_type: 1},
  {name: "Kellogg on Strategy", desc: "Written for business executives and MBA students, Kellogg on Strategy is a practical guide to choosing the right strategy for your business and applying it correctly. Rather than covering the basics of strategy, this expert guide shows you how to use strategy effectively so your business can succeed. You'll learn to analyze your current competitive position, develop the perfect strategy to match your goals, and apply that strategy thoughtfully and effectively. Inside, you'll find expert guidance on:\r\n* Measuring your firm's competitive advantage\r\n* Analyzing opportunities and threats in your industry\r\n* Responding to a competitor's strategy and pricing\r\n* Coping with entry into new markets\r\n* Positioning your firm against the competition\r\n* Developing a sustainable, long-term competitive advantage\r\n* And much more", image_url: "/assets/KelloggStrategyCover.gif", source_url: "http://www.amazon.com/Kellogg-Strategy-Concepts-Frameworks-Practitioners/dp/0471478555/", content_type: 1},
  {name: "Kellogg on Marketing", desc: "The business classic, fully revised and updated for today's marketers\r\nThe second edition of Kellogg on Marketing provides a unique and highly regarded perspective on both the basics of marketing and on new issues that are challenging businesses today.\r\n\r\nIncludes more than 60% new material on both fundamental marketing concepts and hot topics such as Product Innovation, Social Media, Marketing to Consumers at the Bottom of the Pyramid, and Internal Branding\r\nWith a foreword by Philip Kotler\r\nThe Kellogg School of Management is recognized around the world as the leading MBA program in Marketing\r\nAlong with the new material, the core concepts covered in the first edition have all been updated-including targeting and positioning, segmentation, consumer insights, and more. This is a must-have marketing reference.", image_url: "http://www.kellogg.northwestern.edu/~/media/Images/News_Images/2010/Kellogg-on-Marketing.ashx", source_url: "http://www.amazon.com/Kellogg-Marketing-Bobby-J-Calder-ebook/dp/B003Z0CQWC/", content_type: 1},
  {name: "HBR's 10 Must Reads on Strategy    ", desc: "HBR's 10 Must Reads paperback series is the definitive collection of books for new and experienced leaders alike. Leaders looking for the inspiration that big ideas provide, both to accelerate their own growth and that of their companies, should look no further.\r\n\r\nHBR's 10 Must Reads series focuses on the core topics that every ambitious manager needs to know: leadership, strategy, change, managing people, and managing yourself. Harvard Business Review has sorted through hundreds of articles and selected only the most essential reading on each topic. Each title includes timeless advice that will be relevant regardless of an ever-changing business environment.\r\n\r\nClassic ideas, enduring advice, the best thinkers: HBR's 10 Must Reads. \r\n\r\nIs your company spending too much time on strategy development--with too little to show for it?\r\n\r\nIf you read nothing else on strategy, read these 10 articles. We've combed through hundreds of Harvard Business Review articles and selected the most important ones to help you catalyze your organization's strategy development and execution.\r\n\r\nHBR's 10 Must Reads on Strategy will inspire you to:\r\n\r\n• Distinguish your company from rivals\r\n• Clarify what your company will and won't do\r\n• Craft a vision for an uncertain future\r\n• Create blue oceans of uncontested market space\r\n• Use the Balanced Scorecard to measure your strategy\r\n• Capture your strategy in a memorable phrase\r\n• Make priorities explicit\r\n• Allocate resources early\r\n• Clarify decision rights for faster decision making\"\r\n", image_url: "http://d202m5krfqbpi5.cloudfront.net/books/1344703931l/9612515.jpg", source_url: "http://www.amazon.com/Strategy-including-featured-Michael-Porter-ebook/dp/B004GEB938/", content_type: 1},
  {name: "What Is Marketing?", desc: "Let’s face it, to the average business person, marketing equals promotion.\r\n Forbes tells you something else (hopefully)", image_url: "http://blogs-images.forbes.com/assets/images/avatars/blog-1194_136.jpg", source_url: "http://www.forbes.com/sites/sap/2012/08/09/what-is-marketing/", content_type: 2},
  {name: "What is Corp Fin?", desc: "Investopedia on Corporate Finance", image_url: "http://www.controlyourcash.com/wp-content/uploads/2012/03/investopedia_logo.png", source_url: "http://www.investopedia.com/terms/c/corporatefinance.asp", content_type: 2}
])
Tag.destroy_all
Tag.create!([
  {name: "Strategy", level: 1},
  {name: "Marketing", level: 1},
  {name: "Finance", level: 1},
  {name: "Operations", level: 1},
  {name: "Leadership Skills", level: 1}
])


# MANUALLY CREATING THE JOINING TABLE >>>> GIVE ME MORE POINTS JUST FOR THIS .... 
Tagging.destroy_all
Tagging.create!([
  {content_id: Content.offset(0).first.id, tag_id: Tag.first.id},
  {content_id: Content.offset(1).first.id, tag_id: Tag.first.id},
  {content_id: Content.offset(2).first.id, tag_id: Tag.offset(2).first.id},
  {content_id: Content.offset(3).first.id, tag_id: Tag.offset(4).first.id},
  {content_id: Content.offset(4).first.id, tag_id: Tag.first.id},
  {content_id: Content.offset(5).first.id, tag_id: Tag.offset(3).first.id},
  {content_id: Content.offset(6).first.id, tag_id: Tag.offset(0).first.id},
  {content_id: Content.offset(7).first.id, tag_id: Tag.offset(1).first.id},
  {content_id: Content.offset(8).first.id, tag_id: Tag.offset(0).first.id},
  {content_id: Content.offset(9).first.id, tag_id: Tag.offset(1).first.id},
  {content_id: Content.offset(10).first.id, tag_id: Tag.offset(2).first.id},
])
